// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const SHOW_CHANGE_PASSWORD = 'SHOW_CHANGE_PASSWORD';
export const HIDE_CHANGE_PASSWORD = 'HIDE_CHANGE_PASSWORD';

//Sticky
export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE = 'NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS = 'FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS = 'UPDATE_ALL_NOTES_SUCCESS';

//Contact
export const GET_All_CONTACT_SUCCESS = 'GET_All_CONTACT_SUCCESS';
export const ON_ADD_CONTACT_SUCCESS = 'ON_ADD_CONTACT_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';

// Sidebar
export const SET_SEARCH = 'SET_SEARCH';
export const SET_LINK = 'SET_LINK';
export const SET_ACTIVE_MODULE = 'SET_ACTIVE_MODULE';
export const GET_MENU_ITEMS = 'GET_MENU_ITEMS';
export const GET_MENU_ITEMS_SUCCESS = 'GET_MENU_ITEMS_SUCCESS';

// API
export const FETCH_ARTICLE_DETAILS = 'FETCH_ARTICLE_DETAILS';
export const SET_ARTICLE_DETAILS = 'SET_ARTICLE_DETAILS';

export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const API_ERROR = 'API_ERROR';

//JOB
export const JOB_ADD = 'JOB_ADD';
export const JOB_DATA = 'JOB_DATA';
export const JOB_DELETE = 'JOB_DELETE';
export const JOB_UPDATE = 'JOB_UPDATE';

//DEPARTMENT
export const DEPARTMENT_ADD = 'DEPARTMENT_ADD';
export const DEPARTMENT_DATA = 'DEPARTMENT_DATA';
export const DEPARTMENT_DELETE = 'DEPARTMENT_DELETE';
export const DEPARTMENT_UPDATE = 'DEPARTMENT_UPDATE';

//LEVEL
export const LEVEL_ADD = 'LEVEL_ADD';
export const LEVEL_DATA = 'LEVEL_DATA';
export const LEVEL_UPDATE = 'DEPARTMENT_UPDATE';
export const LEVEL_DELETE = 'LEVEL_DELETE';

//ORGANIZTION CHART AND POST
export const ORGANIZTIONCHART_ADD = 'ORGANIZTIONCHART_ADD';
export const ORGANIZTIONCHART_DATA = 'ORGANIZTIONCHART_DATA';
export const ORGANIZTIONCHART_UPDATE = 'ORGANIZTIONCHART_UPDATE';
export const ORGANIZTIONCHART_DELETE = 'ORGANIZTIONCHART_DELETE';

export const ORGANIZTIONCHARTPOST_ADD = 'ORGANIZTIONCHARTPOST_ADD';
export const ORGANIZTIONCHARTPOST_DATA = 'ORGANIZTIONCHARTPOST_DATA';
export const ORGANIZTIONCHARTPOST_UPDATE = 'ORGANIZTIONCHARTPOST_UPDATE';
export const ORGANIZTIONCHARTPOST_DELETE = 'ORGANIZTIONCHARTPOST_DELETE';

export const ORGANIZTIONCHARTPOSTDEP_DATA = 'ORGANIZTIONCHARTPOSTDEP_DATA';
export const ORGANIZTIONCHARTPOSTJOB_DATA = 'ORGANIZTIONCHARTPOSTJOB_DATA';
export const ORGANIZTIONCHARTPOSTLEVEL_DATA = 'ORGANIZTIONCHARTPOSTLEVEL_DATA';

//CHART AND POSITION
export const CHART_ADD = 'CHART_ADD';
export const CHART_DATA = 'CHART_DATA';
export const CHART_UPDATE = 'CHART_UPDATE';
export const CHART_DELETE = 'CHART_DELETE';

export const CHARTTEMPLATE_DATA = 'CHARTTEMPLATE_DATA';
export const CHARTLOCATION_DATA = 'CHARTLOCATION_DATA';

export const CHARTPOSITION_ADD = 'CHARTPOSITION_ADD';
export const CHARTPOSITION_DATA = 'CHARTPOSITION_DATA';
export const CHARTPOSITION_UPDATE = 'CHARTPOSITION_UPDATE';
export const CHARTPOSITION_DELETE = 'CHARTPOSITION_DELETE';

export const CHARTPOSITIONDEP_DATA = 'CHARTPOSITIONDEP_DATA';
export const CHARTPOSITIONJOB_DATA = 'CHARTPOSITIONJOB_DATA';
export const CHARTPOSITIONLEVEL_DATA = 'CHARTPOSITIONLEVEL_DATA';

export const CHARTPOSITIONALLOWEDPOSTS_DATA = 'CHARTPOSITIONALLOWEDPOSTS_DATA';
export const CHARTALLPOSTS_DATA = 'CHARTALLPOSTS_DATA';

export const ALARM_ALARM_MANAGEMENT_ON_SHOW = 'ALARM_ALARM_MANAGEMENT_ON_SHOW';
export const ALARM_ALARM_MANAGEMENT_ON_HIDE = 'ALARM_ALARM_MANAGEMENT_ON_HIDE';
export const ALARM_ALARM_MANAGEMENT_FORM_ON_CHANGE = 'ALARM_ALARM_MANAGEMENT_FORM_ON_CHANGE';

//Customer
export const CUSTOMER_LOAD = 'CUSTOMER_LOAD';
export const CUSTOMER_DATA = 'CUSTOMER_DATA';
export const CUSTOMER_CHEQUE_ON_CHANGE = 'CUSTOMER_CHEQUE_ON_CHANGE';

//Policy //Vahid
export const GET_ERP_POLICY_ENTITY_PROPERTIES_SELL = 'GET_ERP_POLICY_ENTITY_PROPERTIES_SELL';
export const GET_ERP_POLICY_ENTITY_PROPERTIES_SELL_SUCCESS = 'GET_ERP_POLICY_ENTITY_PROPERTIES_SELL_SUCCESS';
export const POLICY_BASIC_INFORMATION_STEP_FORM_ON_CHANGE = 'POLICY_BASIC_INFORMATION_STEP_FORM_ON_CHANGE';
export const POLICY_QUERY_BUILDER_STEP_FORM_ON_CHANGE = 'POLICY_QUERY_BUILDER_STEP_FORM_ON_CHANGE';
export const POLICY_SELECT_BRANCH_STEP_FORM_ON_CHANGE = 'POLICY_SELECT_BRANCH_STEP_FORM_ON_CHANGE';
export const POLICY_RESULT_STEP_FORM_ON_CHANGE = 'POLICY_RESULT_STEP_FORM_ON_CHANGE';
export const POLICY_COLLECTION_RESULT_STEP_FORM_ON_CHANGE = 'POLICY_COLLECTION_RESULT_STEP_FORM_ON_CHANGE';
export const POLICY_CUSTOM_FORM_STEP_ON_CHANGE = 'POLICY_CUSTOM_FORM_STEP_ON_CHANGE';
export const POLICY_DAILY_SELL_SUMMARY_STEP_ON_CHANGE = 'POLICY_DAILY_SELL_SUMMARY_STEP_ON_CHANGE';
export const SET_POLICY_CURRENT_STEP = 'SET_POLICY_CURRENT_STEP';
export const CLEAN_POLICY_STEPS_DATA = 'CLEAN_POLICY_STEPS_DATA';
export const POLICY_INVOICE_CONDITION_STEP_FORM_ON_CHANGE = 'POLICY_INVOICE_CONDITION_STEP_FORM_ON_CHANGE';
export const POLICY_NET_PRODUCT_CUSTOMER_USAGE_LIST_CONDITION_STEP_FORM_ON_CHANGE = 'POLICY_NET_PRODUCT_CUSTOMER_USAGE_LIST_CONDITION_STEP_FORM_ON_CHANGE';
export const GET_INIT_POLICY_STEPS_DATA = 'GET_INIT_POLICY_STEPS_DATA';
export const GET_INIT_POLICY_STEPS_DATA_SUCCESS = 'GET_INIT_POLICY_STEPS_DATA_SUCCESS';
export const GET_POLICY_BASE_POLICY_ALL_RESULT_PRIORITY_TYPE_LIST =
  'GET_POLICY_BASE_POLICY_ALL_RESULT_PRIORITY_TYPE_LIST';
export const GET_POLICY_BASE_POLICY_ALL_RESULT_PRIORITY_TYPE_LIST_SUCCESS =
  'GET_POLICY_BASE_POLICY_ALL_RESULT_PRIORITY_TYPE_LIST_SUCCESS';
export const GET_POLICY_CATEGORY_LIST = 'GET_POLICY_CATEGORY_LIST';
export const GET_POLICY_CATEGORY_LIST_SUCCESS = 'GET_POLICY_CATEGORY_LIST_SUCCESS';
export const GET_POLICY_BASE_POLICY_ALL_POLICY_DURATION_TYPES_LIST =
  'GET_POLICY_BASE_POLICY_ALL_POLICY_DURATION_TYPES_LIST';
export const GET_POLICY_BASE_POLICY_ALL_POLICY_DURATION_TYPES_LIST_SUCCESS =
  'GET_POLICY_BASE_POLICY_ALL_POLICY_DURATION_TYPES_LIST_SUCCESS';
export const GET_POLICY_BASE_POLICY_MEASURES_LIST = 'GET_POLICY_BASE_POLICY_MEASURES_LIST';
export const GET_POLICY_BASE_POLICY_MEASURES_LIST_SUCCESS = 'GET_POLICY_BASE_POLICY_MEASURES_LIST_SUCCESS';

//Sales Target Festival //Vahid
export const GET_ERP_SALES_TARGET_FESTIVAL_ENTITY_PROPERTIES_SELL =
  'GET_ERP_SALES_TARGET_FESTIVAL_ENTITY_PROPERTIES_SELL';
export const GET_ERP_SALES_TARGET_FESTIVAL_ENTITY_PROPERTIES_SELL_SUCCESS =
  'GET_ERP_SALES_TARGET_FESTIVAL_ENTITY_PROPERTIES_SELL_SUCCESS';
export const SALES_TARGET_FESTIVAL_BASIC_INFORMATION_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_FESTIVAL_BASIC_INFORMATION_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_FESTIVAL_QUERY_BUILDER_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_FESTIVAL_QUERY_BUILDER_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_FESTIVAL_SELECT_BRANCH_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_FESTIVAL_SELECT_BRANCH_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_FESTIVAL_RESULT_STEP_FORM_ON_CHANGE = 'SALES_TARGET_FESTIVAL_RESULT_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_FESTIVAL_COLLECTION_RESULT_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_FESTIVAL_COLLECTION_RESULT_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_FESTIVAL_CUSTOM_FORM_STEP_ON_CHANGE = 'SALES_TARGET_FESTIVAL_CUSTOM_FORM_STEP_ON_CHANGE';
export const SALES_TARGET_FESTIVAL_DAILY_SELL_SUMMARY_STEP_ON_CHANGE =
  'SALES_TARGET_FESTIVAL_DAILY_SELL_SUMMARY_STEP_ON_CHANGE';
export const SET_SALES_TARGET_FESTIVAL_CURRENT_STEP = 'SET_SALES_TARGET_FESTIVAL_CURRENT_STEP';
export const CLEAN_SALES_TARGET_FESTIVAL_STEPS_DATA = 'CLEAN_SALES_TARGET_FESTIVAL_STEPS_DATA';
export const SALES_TARGET_FESTIVAL_INVOICE_CONDITION_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_FESTIVAL_INVOICE_CONDITION_STEP_FORM_ON_CHANGE';
export const GET_INIT_SALES_TARGET_FESTIVAL_STEPS_DATA = 'GET_INIT_SALES_TARGET_FESTIVAL_STEPS_DATA';
export const GET_INIT_SALES_TARGET_FESTIVAL_STEPS_DATA_SUCCESS = 'GET_INIT_SALES_TARGET_FESTIVAL_STEPS_DATA_SUCCESS';
export const GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_ALL_RESULT_PRIORITY_TYPE_LIST =
  'GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_ALL_RESULT_PRIORITY_TYPE_LIST';
export const GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_ALL_RESULT_PRIORITY_TYPE_LIST_SUCCESS =
  'GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_ALL_RESULT_PRIORITY_TYPE_LIST_SUCCESS';
export const GET_SALES_TARGET_FESTIVAL_CATEGORY_LIST = 'GET_SALES_TARGET_FESTIVAL_CATEGORY_LIST';
export const GET_SALES_TARGET_FESTIVAL_CATEGORY_LIST_SUCCESS = 'GET_SALES_TARGET_FESTIVAL_CATEGORY_LIST_SUCCESS';
export const GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_ALL_SALES_TARGET_FESTIVAL_DURATION_TYPES_LIST =
  'GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_ALL_SALES_TARGET_FESTIVAL_DURATION_TYPES_LIST';
export const GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_ALL_SALES_TARGET_FESTIVAL_DURATION_TYPES_LIST_SUCCESS =
  'GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_ALL_SALES_TARGET_FESTIVAL_DURATION_TYPES_LIST_SUCCESS';
export const GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_MEASURES_LIST =
  'GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_MEASURES_LIST';
export const GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_MEASURES_LIST_SUCCESS =
  'GET_SALES_TARGET_FESTIVAL_BASE_SALES_TARGET_FESTIVAL_MEASURES_LIST_SUCCESS';
export const SALES_TARGET_FESTIVAL_USERS_OF_BRANCHES_STEP_ON_CHANGE =
  'SALES_TARGET_FESTIVAL_USERS_OF_BRANCHES_STEP_ON_CHANGE';
export const GET_SALES_TARGET_FESTIVAL_EFFICIENCY_REWARD_TYPE_LIST =
  'GET_SALES_TARGET_FESTIVAL_EFFICIENCY_REWARD_TYPE_LIST';
export const GET_SALES_TARGET_FESTIVAL_EFFICIENCY_REWARD_TYPE_LIST_SUCCESS =
  'GET_SALES_TARGET_FESTIVAL_EFFICIENCY_REWARD_TYPE_LIST_SUCCESS';
export const SALES_TARGET_FESTIVAL_PLAN_GOALS_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_FESTIVAL_PLAN_GOALS_STEP_FORM_ON_CHANGE';
export const GET_SALES_TARGET_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_FESTIVAL_PLAN_TYPES =
  'GET_SALES_TARGET_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_FESTIVAL_PLAN_TYPES';
export const GET_SALES_TARGET_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_FESTIVAL_PLAN_TYPES_SUCCESS =
  'GET_SALES_TARGET_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_FESTIVAL_PLAN_TYPES_SUCCESS';
export const GET_SALES_TARGET_FESTIVAL_EFFICIENCY_PLAN_LEVEL_LIST =
  'GET_SALES_TARGET_FESTIVAL_EFFICIENCY_PLAN_LEVEL_LIST';
export const GET_SALES_TARGET_FESTIVAL_EFFICIENCY_PLAN_LEVEL_LIST_SUCCESS =
  'GET_SALES_TARGET_FESTIVAL_EFFICIENCY_PLAN_LEVEL_LIST_SUCCESS';
export const GET_SALES_TARGET_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_RANKING_PLAN_TYPES =
  'GET_SALES_TARGET_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_RANKING_PLAN_TYPES';
export const GET_SALES_TARGET_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_RANKING_PLAN_TYPES_SUCCESS =
  'GET_SALES_TARGET_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_RANKING_PLAN_TYPES_SUCCESS';

//Sales Target Customer Festival //Vahid
export const GET_ERP_SALES_TARGET_CUSTOMER_FESTIVAL_ENTITY_PROPERTIES_SELL =
  'GET_ERP_SALES_TARGET_CUSTOMER_FESTIVAL_ENTITY_PROPERTIES_SELL';
export const GET_ERP_SALES_TARGET_CUSTOMER_FESTIVAL_ENTITY_PROPERTIES_SELL_SUCCESS =
  'GET_ERP_SALES_TARGET_CUSTOMER_FESTIVAL_ENTITY_PROPERTIES_SELL_SUCCESS';
export const SALES_TARGET_CUSTOMER_FESTIVAL_BASIC_INFORMATION_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_CUSTOMER_FESTIVAL_BASIC_INFORMATION_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_CUSTOMER_FESTIVAL_QUERY_BUILDER_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_CUSTOMER_FESTIVAL_QUERY_BUILDER_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_CUSTOMER_FESTIVAL_SELECT_BRANCH_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_CUSTOMER_FESTIVAL_SELECT_BRANCH_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_CUSTOMER_FESTIVAL_RESULT_STEP_FORM_ON_CHANGE = 'SALES_TARGET_CUSTOMER_FESTIVAL_RESULT_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_CUSTOMER_FESTIVAL_COLLECTION_RESULT_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_CUSTOMER_FESTIVAL_COLLECTION_RESULT_STEP_FORM_ON_CHANGE';
export const SALES_TARGET_CUSTOMER_FESTIVAL_CUSTOM_FORM_STEP_ON_CHANGE = 'SALES_TARGET_CUSTOMER_FESTIVAL_CUSTOM_FORM_STEP_ON_CHANGE';
export const SALES_TARGET_CUSTOMER_FESTIVAL_DAILY_SELL_SUMMARY_STEP_ON_CHANGE =
  'SALES_TARGET_CUSTOMER_FESTIVAL_DAILY_SELL_SUMMARY_STEP_ON_CHANGE';
export const SET_SALES_TARGET_CUSTOMER_FESTIVAL_CURRENT_STEP = 'SET_SALES_TARGET_CUSTOMER_FESTIVAL_CURRENT_STEP';
export const CLEAN_SALES_TARGET_CUSTOMER_FESTIVAL_STEPS_DATA = 'CLEAN_SALES_TARGET_CUSTOMER_FESTIVAL_STEPS_DATA';
export const SALES_TARGET_CUSTOMER_FESTIVAL_INVOICE_CONDITION_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_CUSTOMER_FESTIVAL_INVOICE_CONDITION_STEP_FORM_ON_CHANGE';
export const GET_INIT_SALES_TARGET_CUSTOMER_FESTIVAL_STEPS_DATA = 'GET_INIT_SALES_TARGET_CUSTOMER_FESTIVAL_STEPS_DATA';
export const GET_INIT_SALES_TARGET_CUSTOMER_FESTIVAL_STEPS_DATA_SUCCESS = 'GET_INIT_SALES_TARGET_CUSTOMER_FESTIVAL_STEPS_DATA_SUCCESS';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_ALL_RESULT_PRIORITY_TYPE_LIST =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_ALL_RESULT_PRIORITY_TYPE_LIST';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_ALL_RESULT_PRIORITY_TYPE_LIST_SUCCESS =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_ALL_RESULT_PRIORITY_TYPE_LIST_SUCCESS';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_CATEGORY_LIST = 'GET_SALES_TARGET_CUSTOMER_FESTIVAL_CATEGORY_LIST';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_CATEGORY_LIST_SUCCESS = 'GET_SALES_TARGET_CUSTOMER_FESTIVAL_CATEGORY_LIST_SUCCESS';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_ALL_SALES_TARGET_CUSTOMER_FESTIVAL_DURATION_TYPES_LIST =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_ALL_SALES_TARGET_CUSTOMER_FESTIVAL_DURATION_TYPES_LIST';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_ALL_SALES_TARGET_CUSTOMER_FESTIVAL_DURATION_TYPES_LIST_SUCCESS =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_ALL_SALES_TARGET_CUSTOMER_FESTIVAL_DURATION_TYPES_LIST_SUCCESS';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_MEASURES_LIST =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_MEASURES_LIST';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_MEASURES_LIST_SUCCESS =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_BASE_SALES_TARGET_CUSTOMER_FESTIVAL_MEASURES_LIST_SUCCESS';
export const SALES_TARGET_CUSTOMER_FESTIVAL_USERS_OF_BRANCHES_STEP_ON_CHANGE =
  'SALES_TARGET_CUSTOMER_FESTIVAL_USERS_OF_BRANCHES_STEP_ON_CHANGE';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_REWARD_TYPE_LIST =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_REWARD_TYPE_LIST';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_REWARD_TYPE_LIST_SUCCESS =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_REWARD_TYPE_LIST_SUCCESS';
export const SALES_TARGET_CUSTOMER_FESTIVAL_PLAN_GOALS_STEP_FORM_ON_CHANGE =
  'SALES_TARGET_CUSTOMER_FESTIVAL_PLAN_GOALS_STEP_FORM_ON_CHANGE';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_FESTIVAL_PLAN_TYPES =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_FESTIVAL_PLAN_TYPES';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_FESTIVAL_PLAN_TYPES_SUCCESS =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_FESTIVAL_PLAN_TYPES_SUCCESS';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_PLAN_LEVEL_LIST =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_PLAN_LEVEL_LIST';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_PLAN_LEVEL_LIST_SUCCESS =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_PLAN_LEVEL_LIST_SUCCESS';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_RANKING_PLAN_TYPES =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_RANKING_PLAN_TYPES';
export const GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_RANKING_PLAN_TYPES_SUCCESS =
  'GET_SALES_TARGET_CUSTOMER_FESTIVAL_EFFICIENCY_BASE_FESTIVAL_ALL_RANKING_PLAN_TYPES_SUCCESS';

// Quota //Vahid
export const QUOTA_INSERT_INFORMATION_FORM_STEP_ON_CHANGE = 'QUOTA_INSERT_INFORMATION_FORM_STEP_ON_CHANGE';
export const QUOTA_SELECT_PRODUCTS_STEP_ON_CHANGE = 'QUOTA_SELECT_PRODUCTS_STEP_ON_CHANGE';
export const SET_QUOTA_INSERT_CURRENT_STEP = 'SET_QUOTA_INSERT_CURRENT_STEP';
export const CLEAN_QUOTA_STEPS_DATA = 'CLEAN_QUOTA_STEPS_DATA';
export const QUOTA_SELECT_VISITORS_STEP_ON_CHANGE = 'QUOTA_SELECT_VISITORS_STEP_ON_CHANGE';
export const QUOTA_VISITORS_ON_CHANGE = 'QUOTA_VISITORS_ON_CHANGE';
export const GET_INIT_QUOTA_STEPS_DATA = 'GET_INIT_QUOTA_STEPS_DATA';
export const GET_INIT_QUOTA_STEPS_DATA_SUCCESS = 'GET_INIT_QUOTA_STEPS_DATA_SUCCESS';

//ProductManagement //bijan
// export const PRODUCTS_GET_PRODUCT_LIST = 'PRODUCTS_GET_PRODUCT_LIST';
// export const PRODUCTS_GET_PRODUCT_LIST_SUCCESS = 'PRODUCTS_GET_PRODUCT_LIST_SUCCESS';
export const PRODUCT_MANAGEMENT_LICENCE_ON_CHANGE = 'PRODUCTS_GET_LICENCE_ON_CHANGE';
export const PRODUCT_MANAGEMENT_GROUP_ON_CHANGE = 'PRODUCTS_GROUP_ON_CHANGE';
export const PRODUCT_MANAGEMENT_BASKET_ON_CHANGE = 'PRODUCTS_BASKET_ON_CHANGE';
export const PRODUCT_MANAGEMENT_UNIT_PRODUCT_ON_CHANGE = 'PRODUCTS_UNIT_PRODUCT_ON_CHANGE';
export const PRODUCT_MANAGEMENT_PRODUCT_GROUP_SPECIALTY_ON_CHANGE = 'PRODUCTS_PRODUCT_GROUP_SPECIALTY_ON_CHANGE';
export const PRODUCT_MANAGEMENT_BATCH_PRODUCT_ON_CHANGE = 'PRODUCT_BATCH_PRODUCT_ON_CHANGE';
export const PRODUCT_MANAGEMENT_IRC_ON_CHANGE = 'PRODUCT_IRC_ON_CHANGE';

export const PRODUCT_MANAGEMENT_EMPHASIS_ON_CHANGE = 'PRODUCT_EMPHASIS_ON_CHANGE';
export const PRODUCT_MANAGEMENT_PRODUCT_ON_CHANGE = 'PRODUCT_MANAGEMENT_PRODUCT_ON_CHANGE';
export const PRODUCT_MANAGEMENT_VISITOR_PRODUCT_ON_CHANGE = 'PRODUCT_MANAGEMENT_VISITOR_PRODUCT_ON_CHANGE';

//ProductManagement //Vahid
export const PRODUCT_BASKET_INFORMATION_STEP_FORM_ON_CHANGE = 'PRODUCT_BASKET_INFORMATION_STEP_FORM_ON_CHANGE';
export const PRODUCT_BASKET_PRODUCTS_VALUES_STEP_ON_CHANGE = 'PRODUCT_BASKET_PRODUCTS_VALUES_STEP_ON_CHANGE';
export const PRODUCT_BASKET_SELECT_BRANCH_STEP_FORM_ON_CHANGE = 'PRODUCT_BASKET_SELECT_BRANCH_STEP_FORM_ON_CHANGE';
export const SET_PRODUCT_BASKET_CURRENT_STEP = 'SET_PRODUCT_BASKET_CURRENT_STEP';
export const CLEAN_PRODUCT_BASKET_STEPS_DATA = 'CLEAN_PRODUCT_BASKET_STEPS_DATA';

//SaleManagement Request //Vahid
export const SALE_MANAGEMENT_REQUEST_INFORMATION_STEP_FORM_ON_CHANGE =
  'SALE_MANAGEMENT_REQUEST_INFORMATION_STEP_FORM_ON_CHANGE';
export const SALE_MANAGEMENT_REQUEST_PRODUCTS_VALUES_STEP_ON_CHANGE =
  'SALE_MANAGEMENT_REQUEST_PRODUCTS_VALUES_STEP_ON_CHANGE';
export const SET_SALE_MANAGEMENT_REQUEST_CURRENT_STEP = 'SET_SALE_MANAGEMENT_REQUEST_CURRENT_STEP';
export const CLEAN_SALE_MANAGEMENT_REQUEST_STEPS_DATA = 'CLEAN_SALE_MANAGEMENT_REQUEST_STEPS_DATA';

//Global Values
export const GET_ACCESS_USER_BRANCHES_LIST = 'GET_ACCESS_USER_BRANCHES_LIST';
export const GET_ACCESS_USER_BRANCHES_LIST_SUCCESS = 'GET_ACCESS_USER_BRANCHES_LIST_SUCCESS';
export const GET_ACCESS_USER_KINDS_LIST = 'GET_ACCESS_USER_KINDS_LIST';
export const GET_ACCESS_USER_KINDS_LIST_SUCCESS = 'GET_ACCESS_USER_KINDS_LIST_SUCCESS';
export const GET_SUPPLIERS_LIST = 'GET_SUPPLIERS_LIST';
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_POLICY_MARJA_SIASATGOZARI_LIST = 'GET_POLICY_MARJA_SIASATGOZARI_LIST';
export const GET_POLICY_MARJA_SIASATGOZARI_LIST_SUCCESS = 'GET_POLICY_MARJA_SIASATGOZARI_LIST_SUCCESS';

//Ag Grid Global Values
export const SET_GLOBAL_VALUES_AG_GRID_STATE_ON_CHANGE = 'SET_GLOBAL_VALUES_AG_GRID_STATE_ON_CHANGE';
export const CLEAN_GLOBAL_VALUES_AG_GRID_ROW_DATA_ON_CHANGE = 'CLEAN_GLOBAL_VALUES_AG_GRID_ROW_DATA_ON_CHANGE';
export const ADD_GLOBAL_VALUES_AG_GRID_ROW_DATA_ON_CHANGE = 'ADD_GLOBAL_VALUES_AG_GRID_ROW_DATA_ON_CHANGE';
export const REMOVE_GLOBAL_VALUES_AG_GRID_ROW_DATA_ON_CHANGE = 'REMOVE_GLOBAL_VALUES_AG_GRID_ROW_DATA_ON_CHANGE';
export const UPDATE_GLOBAL_VALUES_AG_GRID_ROW_DATA_ON_CHANGE = 'UPDATE_GLOBAL_VALUES_AG_GRID_ROW_DATA_ON_CHANGE';
export const SET_GLOBAL_VALUES_CURRENT_ROUTE_ON_CHANGE = 'SET_GLOBAL_VALUES_CURRENT_ROUTE_ON_CHANGE';

//Global Values Tabs state, Vahid
export const SET_GLOBAL_VALUES_TAB_STATE_ON_CHANGE = 'SET_GLOBAL_VALUES_TAB_STATE_ON_CHANGE';

export const SET_GLOBAL_VALUES_FORM_BUILDER_STATE_ON_CHANGE = 'SET_GLOBAL_VALUES_FORM_BUILDER_STATE_ON_CHANGE';

export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_SUCCESS';
//UserProfile
export const GET_ERP_USER_PROFILE_USER_INFO = 'GET_ERP_USER_PROFILE_USER_INFO';
export const GET_ERP_USER_PROFILE_USER_INFO_SUCCESS = 'GET_ERP_USER_PROFILE_USER_INFO_SUCCESS';

//SuppliersManagement
export const SUPPLY_SUPPLIER_ON_CHANGE = 'SUPPLY_SUPPLIER_ON_CHANGE';
export const SUPPLY_SUPPLIER_SUPPLIER_TEL_ON_CHANGE = 'SUPPLY_SUPPLIER_SUPPLIER_TEL_ON_CHANGE';
export const SUPPLY_EMPHASIS_SUPPLIER_ON_CHANGE = 'SUPPLY_EMPHASIS_SUPPLIER_ON_CHANGE';

//OnlineStoreRequest
export const ONLINE_STORE_MANAGEMENT_BANNER_ON_CHANGE = 'ONLINE_STORE_MANAGEMENT_BANNER_ON_CHANGE';
export const ONLINE_STORE_MANAGEMENT_BRAND_ON_CHANGE = 'ONLINE_STORE_MANAGEMENT_BRAND_ON_CHANGE';
export const ONLINE_STORE_MANAGEMENT_FEATURE_ON_CHANGE = 'ONLINE_STORE_MANAGEMENT_FEATURE_ON_CHANGE';
export const ONLINE_STORE_MANAGEMENT_TOP_CATEGORY_ON_CHANGE = 'ONLINE_STORE_MANAGEMENT_TOP_CATEGORY_ON_CHANGE';

//SystemManagement
export const SYSTEM_MANAGEMENT_SOFTWARE_ACCESS_STRUCTURE_ON_CHANGE =
  'SYSTEM_MANAGEMENT_SOFTWARE_ACCESS_STRUCTURE_ON_CHANGE';
export const SYSTEM_MANAGEMENT_ACCESS_ROLE_ON_CHANGE = 'SYSTEM_MANAGEMENT_ACCESS_ROLE_ON_CHANGE';
export const SYSTEM_MANAGEMENT_GROUP_ACCESS_ON_CHANGE = 'SYSTEM_MANAGEMENT_GROUP_ACCESS_ON_CHANGE';
export const SYSTEM_MANAGEMENT_ALL_SOFTWARE_ACCESS_ROLE_ON_LOAD = 'SYSTEM_MANAGEMENT_ALL_SOFTWARE_ACCESS_ROLE_ON_LOAD';
export const SYSTEM_MANAGEMENT_ALL_SOFTWARE_ACCESS_ROLE_ON_LOAD_SUCCESS =
  'SYSTEM_MANAGEMENT_ALL_SOFTWARE_ACCESS_ROLE_ON_LOAD_SUCCESS';
export const SYSTEM_MANAGEMENT_ROLE_SOFTWARE_ACCESS_ROLE_ON_LOAD =
  'SYSTEM_MANAGEMENT_ROLE_SOFTWARE_ACCESS_ROLE_ON_LOAD';
export const SYSTEM_MANAGEMENT_ROLE_SOFTWARE_ACCESS_ROLE_ON_LOAD_SUCCESS =
  'SYSTEM_MANAGEMENT_ROLE_SOFTWARE_ACCESS_ROLE_ON_LOAD_SUCCESS';
export const SYSTEM_MANAGEMENT_ROLE_ACCESS_ITEM_ON_LOAD = 'SYSTEM_MANAGEMENT_ROLE_ACCESS_ITEM_ON_LOAD';
export const SYSTEM_MANAGEMENT_ROLE_ACCESS_ITEM_ON_LOAD_SUCCESS = 'SYSTEM_MANAGEMENT_ROLE_ACCESS_ITEM_ON_LOAD_SUCCESS';
export const SYSTEM_MANAGEMENT_ALL_ACCESS_ITEM_ON_LOAD = 'SYSTEM_MANAGEMENT_ALL_ACCESS_ITEM_ON_LOAD';
export const SYSTEM_MANAGEMENT_ALL_ACCESS_ITEM_ON_LOAD_SUCCESS = 'SYSTEM_MANAGEMENT_ALL_ACCESS_ITEM_ON_LOAD_SUCCESS';
export const SYSTEM_MANAGEMENT_GROUP_ACCESS_ACCESS_ITEM_ON_LOAD = 'SYSTEM_MANAGEMENT_GROUP_ACCESS_ACCESS_ITEM_ON_LOAD';
export const SYSTEM_MANAGEMENT_GROUP_ACCESS_ACCESS_ITEM_ON_LOAD_SUCCESS =
  'SYSTEM_MANAGEMENT_GROUP_ACCESS_ACCESS_ITEM_ON_LOAD_SUCCESS';
export const SYSTEMMANAGEMENT_ORGAN_CHART_ON_CHANGE = 'SYSTEMMANAGEMENT_ORGAN_CHART_ON_CHANGE'; //ahid naeimi

//BaseInfo
export const BASE_INFO_KIND_ON_CHANGE = 'BASE_INFO_KIND_ON_CHANGE';
export const BASE_INFO_WAREHOUSE_ON_CHANGE = 'BASE_INFO_WAREHOUSE_ON_CHANGE';
export const BASE_INFO_BRANCH_ON_CHANGE = 'BASE_INFO_BRANCH_ON_CHANGE';
export const BASE_INFO_JOB_ON_CHANGE = 'BASE_INFO_JOB_ON_CHANGE';
export const BASE_INFO_DEPARTMENT_ON_CHANGE = 'BASE_INFO_DEPARTMENT_ON_CHANGE';
export const BASE_INFO_ORGANIZATION_LEVEL_ON_CHANGE = 'BASE_INFO_ORGANIZATION_LEVEL_ON_CHANGE';
export const BASE_INFO_POLICY_SOURCE_ON_CHANGE = 'BASE_INFO_POLICY_SOURCE_ON_CHANGE';

//UserManagement //ahid naimi
export const USERMANAGEMENT_CHART_ON_CHANGE = 'USERMANAGEMENT_CHART_ON_CHANGE';
export const CHART_TEMPLATE_ON_CHANGE = 'CHART_TEMPLATE_ON_CHANGE';
export const CHART_ADD_UPDATE_DATA = 'CHART_ADD_UPDATE_DATA';
export const ORGANIZATION_LOCATION_ON_CHANGE = 'ORGANIZATION_LOCATION_ON_CHANGE';
export const GET_BASE_INFO_ORGANIZATION_LOCATION_LIST = 'GET_BASE_INFO_ORGANIZATION_LOCATION_LIST';
export const GET_BASE_INFO_ORGANIZATION_LOCATION_LIST_SUCCESS = 'GET_BASE_INFO_ORGANIZATION_LOCATION_LIST_SUCCESS';

//UserManagement //bijan
export const USER_MANAGEMENT_USER_RESPONSIBILITY_ON_CHANGE = 'USER_MANAGEMENT_USER_RESPONSIBILITY_ON_CHANGE';
export const USER_MANAGEMENT_USER_ON_CHANGE = 'USER_MANAGEMENT_USER_ON_CHANGE';
export const USER_INFORMATION_ON_SHOW = 'USER_INFORMATION_ON_SHOW';
export const USER_INFORMATION_USER_KIND_ON_LOAD = 'USER_INFORMATION_USER_KIND_ON_LOAD';
export const USER_INFORMATION_USER_KIND_ON_LOAD_SUCCESS = 'USER_INFORMATION_USER_KIND_ON_LOAD_SUCCESS';
export const USER_INFORMATION_USER_BRANCH_ON_LOAD = 'USER_INFORMATION_USER_BRANCH_ON_LOAD';
export const USER_INFORMATION_USER_BRANCH_ON_LOAD_SUCCESS = 'USER_INFORMATION_USER_BRANCH_ON_LOAD_SUCCESS';
export const USER_INFORMATION_USER_ROLE_ON_LOAD = 'USER_INFORMATION_USER_ROLE_ON_LOAD';
export const USER_INFORMATION_USER_ROLE_ON_LOAD_SUCCESS = 'USER_INFORMATION_USER_ROLE_ON_LOAD_SUCCESS';
export const USER_INFORMATION_USER_ROW_ACCESS_LEVEL_ON_LOAD = 'USER_INFORMATION_USER_ROW_ACCESS_LEVEL_ON_LOAD';
export const USER_INFORMATION_USER_ROW_ACCESS_LEVEL_ON_LOAD_SUCCESS =
  'USER_INFORMATION_USER_ROW_ACCESS_LEVEL_ON_LOAD_SUCCESS';
export const USER_INFORMATION_ON_CHANGE = 'USER_INFORMATION_ON_CHANGE';
export const USER_INFORMATION_USER_PROFILE_INFORMATION_ON_LOAD = 'USER_INFORMATION_USER_PROFILE_INFORMATION_ON_LOAD';
export const USER_INFORMATION_USER_PROFILE_INFORMATION_ON_LOAD_SUCCESS =
  'USER_INFORMATION_USER_PROFILE_INFORMATION_ON_LOAD_SUCCESS';
export const USER_RESPONSIBILITY_USER_INFORMATION_ON_ROUTE = 'USER_RESPONSIBILITY_USER_INFORMATION_ON_ROUTE';

//Role //bijan
export const ACCESS_ROLE_ON_LOAD = 'ACCESS_ROLE_ON_LOAD';
export const ACCESS_ROLE_ON_LOAD_SUCCESS = 'ACCESS_ROLE_ON_LOAD_SUCCESS';

//VisitManagement //bijan
export const VISIT_MANAGEMENT_VISITOR_ON_CHANGE = 'VISIT_MANAGEMENT_VISITOR_ON_CHANGE';

//SaleManagment //Torkian
export const SALE_MANAGEMENT_INVOICE_ON_CHANGE = 'SALE_MANAGEMENT_INVOICE_ON_CHANGE';
export const SALE_MANAGEMENT_REQUEST_ON_CHANGE = 'SALE_MANAGEMENT_REQUEST_ON_CHANGE';
export const SALE_MANAGEMENT_CUSTOMER_REQUEST_ON_CHANGE = 'SALE_MANAGEMENT_CUSTOMER_REQUEST_ON_CHANGE';
export const SALE_MANAGEMENT_ONLINE_STORE_REQUEST_ON_CHANGE = 'SALE_MANAGEMENT_ONLINE_STORE_REQUEST_ON_CHANGE';
export const SALE_MANAGEMENT_CUSTOMER_REQUEST_DETAIL_ON_CHANGE = 'SALE_MANAGEMENT_CUSTOMER_REQUEST_DETAIL_ON_CHANGE';
export const SUPPLIER_PAYMENT_ON_CHANGE = 'SUPPLIER_PAYMENT_ON_CHANGE';

//MAP /ahid
//export const MAP_EXTENT_ON_STATE_CHANGE = 'MAP_EXTENT_ON_STATE_CHANGE';
export const SET_MAP_EXTENT_STATE = 'SET_MAP_EXTENT_STATE';
export const GET_SPEED_AVL = 'GET_SPEED_AVL';
export const SELECTED_GRAPHIC_POINT = 'SELECTED_GRAPHIC_POINT';
export const SHOW_HISTORY_WINDOW = 'SHOW_HISTORY_WINDOW';

//WarehouseSchedule
export const WAREHOUSE_SCHEDULE_ON_CHANGE = 'WAREHOUSE_SCHEDULE_ON_CHANGE';
export const WAREHOUSE_TAG_ON_CHANGE = 'WAREHOUSE_TAG_ON_CHANGE';
export const USER_DEFINE_ON_CHANGE = 'USER_DEFINE_ON_CHANGE';
export const SCHEDULE_WAREHOUSE_GROUP_ON_CHANGE = 'SCHEDULE_WAREHOUSE_GROUP_ON_CHANGE';

//RowLevelAccess //bijan
export const ROW_LEVEL_ACCESS_ROLE_ON_LOAD = 'ROW_LEVEL_ACCESS_ROLE_ON_LOAD';
export const ROW_LEVEL_ACCESS_ROLE_ON_LOAD_SUCCESS = 'ROW_LEVEL_ACCESS_ROLE_ON_LOAD_SUCCESS';

//collection
export const COLLECTION_FINANCIALDAY_CHANGE = 'COLLECTION_FINANCIALDAY_CHANGE'
export const COLLECTION_CUSTOMERACCOUNT_CHANGE = 'COLLECTION_CUSTOMERACCOUNT_CHANGE'
export const COLLECTION_FINANCIALDAY_REGISTER_RECEIVER = 'COLLECTION_FINANCIALDAY_REGISTER_RECEIVER'
export const SET_COLLECTION_FINANCIALDAY_CURRENT_STEP = 'SET_COLLECTION_FINANCIALDAY_CURRENT_STEP'

export const FINANCE_BASE_RECEIPT_METHOD = 'FINANCE_BASE_RECEIPT_METHOD';
export const FINANCE_BASE_RECEIPT_TYPE = 'FINANCE_BASE_RECEIPT_TYPE';
export const FINANCE_BASE_FINDOC_TYPE = 'FINANCE_BASE_FINDOC_TYPE';
export const FINANCE_BASE_COLLECTION_TYPE = 'FINANCE_BASE_COLLECTION_TYPE';
export const FINANCE_BASE_TEMPSETTLEMENT_STATUS = 'FINANCE_BASE_TEMPSETTLEMENT_STATUS';
export const FINANCE_BASE_ACCOUNT_TYPE = 'FINANCE_BASE_ACCOUNT_TYPE';
export const FINANCE_BASE_CHEQUE_STATUS = 'FINANCE_BASE_CHEQUE_STATUS';
export const FINANCE_BASE_PAYMENT_TYPE = 'FINANCE_BASE_PAYMENT_TYPE';
export const FINANCE_BASE_SETTLEMENT_TYPE = 'FINANCE_BASE_SETTLEMENT_TYPE';
export const FINANCE_BASE = 'FINANCE_BASE';
export const FINANCE_BASE_ENUMS = 'FINANCE_BASE_ENUMS';
export const COLLECTION_CUSTOMER_MATCH_ITEM = 'COLLECTION_CUSTOMER_MATCH_ITEM';
export const FINANCE_BASE_RECEIPTGROUP_TYPE = 'FINANCE_BASE_RECEIPTGROUP_TYPE';
export const FINANCE_BASE_BRANCHDETAIL_STATUS = 'FINANCE_BASE_BRANCHDETAIL_STATUS'
export const FINANCE_BASE_BRANCHDETAIL_PERMIT_STATUS = 'FINANCE_BASE_BRANCHDETAIL_PERMIT_STATUS'
